/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\valentinesDay.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/valentinesDay.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube001.geometry} material={materials.brick} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.PlasticMoldWood006_2K} />
      <mesh geometry={nodes.Cube.geometry} material={materials.brick} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.PlasticMoldWood006_2K} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.Cube007.geometry} material={materials.book_shelf} />
      <mesh geometry={nodes.IVY_Curve.geometry} material={nodes.IVY_Curve.material}>
        <mesh geometry={nodes.IvyLeaf.geometry} material={materials['Material.003']} />
      </mesh>
      <mesh geometry={nodes.IVY_Curve001.geometry} material={nodes.IVY_Curve001.material}>
        <mesh geometry={nodes.IvyLeaf001.geometry} material={materials['Material.003']} />
      </mesh>
      <mesh geometry={nodes.IVY_Curve002.geometry} material={nodes.IVY_Curve002.material}>
        <mesh geometry={nodes.IvyLeaf002.geometry} material={materials['Material.003']} />
      </mesh>
      <mesh geometry={nodes.IVY_Curve003.geometry} material={nodes.IVY_Curve003.material}>
        <mesh geometry={nodes.IvyLeaf003.geometry} material={nodes.IvyLeaf003.material} />
      </mesh>
      <mesh geometry={nodes.IVY_Curve004.geometry} material={nodes.IVY_Curve004.material}>
        <mesh geometry={nodes.IvyLeaf004.geometry} material={materials['Material.003']} />
      </mesh>
      <mesh geometry={nodes.BézierCurve.geometry} material={nodes.BézierCurve.material}>
        <mesh geometry={nodes.Sphere.geometry} material={materials['Material.004']} position={[-0.854, 6.772, 7.481]} scale={0.282} />
      </mesh>
      <mesh geometry={nodes.Text.geometry} material={materials['Material.007']} position={[-0.508, 3.857, 7.677]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.619} />
      <mesh geometry={nodes.Cube011.geometry} material={materials.book_shelf} />
      <mesh geometry={nodes.Cube012.geometry} material={materials.brick} />
      <mesh geometry={nodes.Cube013.geometry} material={materials['Material.005']} />
      <mesh geometry={nodes.Empty001.geometry} material={materials.Empty} />
      <mesh geometry={nodes.IVY_Curve005.geometry} material={nodes.IVY_Curve005.material}>
        <mesh geometry={nodes.IvyLeaf005.geometry} material={materials['Material.003']} />
      </mesh>
      <mesh geometry={nodes.IVY_Curve006.geometry} material={nodes.IVY_Curve006.material}>
        <mesh geometry={nodes.IvyLeaf006.geometry} material={materials['Material.003']} />
      </mesh>
      <mesh geometry={nodes.IVY_Curve007.geometry} material={nodes.IVY_Curve007.material}>
        <mesh geometry={nodes.IvyLeaf007.geometry} material={materials['Material.003']} />
      </mesh>
      <mesh geometry={nodes.IVY_Curve008.geometry} material={nodes.IVY_Curve008.material}>
        <mesh geometry={nodes.IvyLeaf008.geometry} material={materials['Material.003']} />
      </mesh>
      <mesh geometry={nodes.Empty003.geometry} material={materials['Empty.002']} />
      <mesh geometry={nodes.fireplace_fireplace_0.geometry} material={materials.fireplace} />
      <mesh geometry={nodes.Book_0.geometry} material={materials.Book} />
      <mesh geometry={nodes.Book_1.geometry} material={materials['Material.012']} />
      <mesh geometry={nodes.Book001_0.geometry} material={materials.Book} />
      <mesh geometry={nodes.Book001_1.geometry} material={materials['Material.014']} />
      <mesh geometry={nodes.Book002_0.geometry} material={materials.Book} />
      <mesh geometry={nodes.Book002_1.geometry} material={materials['Material.012']} />
      <mesh geometry={nodes.Book003_0.geometry} material={materials.Book} />
      <mesh geometry={nodes.Book003_1.geometry} material={materials['Material.013']} />
      <mesh geometry={nodes.Book003_1001.geometry} material={materials['Material.013']} />
      <mesh geometry={nodes.Book003_1002.geometry} material={materials['Material.013']} />
      <mesh geometry={nodes.Book004_0.geometry} material={materials.Book} />
      <mesh geometry={nodes.Book004_1.geometry} material={materials['Material.012']} />
      <mesh geometry={nodes.Book005_0.geometry} material={materials.Book} />
      <mesh geometry={nodes.Book005_1.geometry} material={materials['Material.014']} />
      <mesh geometry={nodes.Book005_1001.geometry} material={materials['Material.014']} />
      <mesh geometry={nodes.Book006_0.geometry} material={materials.Book} />
      <mesh geometry={nodes.Book006_1.geometry} material={materials['Material.012']} />
      <mesh geometry={nodes.Book006_1001.geometry} material={materials['Material.012']} />
      <mesh geometry={nodes.Book007_0.geometry} material={materials.Book} />
      <mesh geometry={nodes.Book007_1.geometry} material={materials['Material.013']} />
      <mesh geometry={nodes.Book007_1001.geometry} material={materials['Material.013']} />
      <mesh geometry={nodes.Book008_0.geometry} material={materials.Book} />
      <mesh geometry={nodes.Book008_1.geometry} material={materials['Material.013']} />
      <mesh geometry={nodes.Book009_0.geometry} material={materials.Book} />
      <mesh geometry={nodes.Book009_1.geometry} material={materials['Material.014']} />
      <mesh geometry={nodes.Book010_0.geometry} material={materials.Book} />
      <mesh geometry={nodes.Book010_1.geometry} material={materials['Material.012']} />
      <mesh geometry={nodes.Book011_0.geometry} material={materials.Book} />
      <mesh geometry={nodes.Book011_1.geometry} material={materials['Material.013']} />
      <mesh geometry={nodes.book_shelf_0.geometry} material={materials.PlasticMoldWood006_2K} />
      <mesh geometry={nodes.book_shelf_0002.geometry} material={materials.PlasticMoldWood006_2K} />
      <mesh geometry={nodes.book_shelf_0001.geometry} material={materials.PlasticMoldWood006_2K} />
      <mesh geometry={nodes.book_shelf_0003.geometry} material={materials.PlasticMoldWood006_2K} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.Leather} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.Leather} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.Leather} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.Leather} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.blanket} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.Leather} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.metal} />
      <mesh geometry={nodes.Object_21.geometry} material={materials.Leather} />
      <mesh geometry={nodes.Object_23.geometry} material={materials.Leather} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.Leather} />
      <mesh geometry={nodes.Object_27.geometry} material={materials.Leather} />
      <mesh geometry={nodes.Object_25.geometry} material={materials.Leather} />
      <mesh geometry={nodes.Object_29.geometry} material={materials.Leather} />
      <mesh geometry={nodes.Object_33.geometry} material={materials.Fabric_pilows} />
      <mesh geometry={nodes.Object_35.geometry} material={materials.Fabric_pilows} />
      <mesh geometry={nodes.Object_31.geometry} material={materials.Fabric_pilows} />
      <mesh geometry={nodes.group49_pCylinder59_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.group49_pCylinder60_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.group49_pCylinder61_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.group49_pCylinder62_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.group49_pCylinder63_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.group49_pCylinder64_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.group49_pCylinder65_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.group49_pCylinder66_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.group49_pCylinder67_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.group49_pCylinder68_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.group49_pCylinder69_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.group49_pCylinder70_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.group49_pCylinder71_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.Mesh_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.pCube39_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.pCylinder137_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.pCylinder138_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.pCylinder139_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.pCylinder140_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.pCylinder141_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.pCylinder142_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.pCylinder143_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.pCylinder144_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.pCylinder145_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.pCylinder146_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.pCylinder147_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.pCylinder148_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.pCylinder149_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.pCylinder150_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.pCylinder151_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.pCylinder152_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.pCylinder153_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.pCylinder154_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.pCylinder155_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.pCylinder156_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.pCylinder157_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.pCylinder158_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.polySurface136_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.polySurface137_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.polySurface138_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.polySurface139_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.polySurface140_aiStandardSurface2_0.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.WineBottles001_01001.geometry} material={materials.WineBottles001_4K} />
      <mesh geometry={nodes.WineBottles001_02001.geometry} material={materials.WineBottles001_4K} />
      <mesh geometry={nodes.WineBottles001_03001.geometry} material={materials.WineBottles001_4K} />
      <mesh geometry={nodes.BottleSodaEmpty001_Bottle001.geometry} material={materials.BottleSodaEmpty001_1K} />
      <mesh geometry={nodes.BottleSodaEmpty001_Cap001.geometry} material={materials.BottleSodaEmpty001_1K} />
      <mesh geometry={nodes.BottleSodaEmpty001_Bottle002.geometry} material={materials.BottleSodaEmpty001_1K} />
      <mesh geometry={nodes.BottleSodaEmpty001_Cap002.geometry} material={materials.BottleSodaEmpty001_1K} />
      <mesh geometry={nodes.RugDesignerAlbatrossGrey001001.geometry} material={materials.RugDesignerAlbatrossGrey001_4K} position={[-0.693, -0.377, 3.035]} scale={1.136} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.outlines} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.glep} />
      <mesh geometry={nodes.Object_13001.geometry} material={materials.outlines} />
      <mesh geometry={nodes.Object_15001.geometry} material={materials.glep} />
      <mesh geometry={nodes.Object_17001.geometry} material={materials.glep} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.outlines} />
      <mesh geometry={nodes.Object_7001.geometry} material={materials.glep} />
      <mesh geometry={nodes.Object_9001.geometry} material={materials.glep} />
    </group>
  )
}

useGLTF.preload('/valentinesDay.glb')
