/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\valentines_day_scene.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/valentines_day_scene.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.821, -0.465, 1.028]} scale={[0.391, 0.41, 0.391]}>
        <mesh geometry={nodes.WindowSlidingPaintedMetal002_Frame_Geo_LOD0001.geometry} material={materials.WindowSlidingPaintedMetal002_Window_Mat_LOD0_8K_VAR1_8K} position={[0, -0.012, -0.051]} scale={[1.021, 1, 1]} />
        <mesh geometry={nodes.WindowSlidingPaintedMetal002_LeftSash_Geo_LOD0001.geometry} material={materials.WindowSlidingPaintedMetal002_Window_Mat_LOD0_8K_VAR1_8K} position={[0, -0.012, -0.051]} />
        <mesh geometry={nodes.WindowSlidingPaintedMetal002_RightSash_Geo_LOD0001.geometry} material={materials.WindowSlidingPaintedMetal002_Window_Mat_LOD0_8K_VAR1_8K} position={[0, -0.012, -0.051]} />
      </group>
      <group position={[-0.568, -0.464, 1.013]} scale={0.293}>
        <mesh geometry={nodes.InteriorDoorFrench002_DoorL_Geo_LOD0002.geometry} material={materials['InteriorDoorFrench002_Door_Mat_LOD0_8K_VAR1_8K.001']} position={[0, -0.024, 0]} />
        <mesh geometry={nodes.InteriorDoorFrench002_DoorR_Geo_LOD0002.geometry} material={materials['InteriorDoorFrench002_Door_Mat_LOD0_8K_VAR1_8K.001']} position={[0, -0.024, 0]} />
        <mesh geometry={nodes.InteriorDoorFrench002_Frame_Geo_LOD0002.geometry} material={materials['InteriorDoorFrench002_Door_Mat_LOD0_8K_VAR1_8K.001']} position={[0, -0.034, 0]} scale={1.007} />
        <mesh geometry={nodes.InteriorDoorFrench002_HandleL_Geo_LOD0002.geometry} material={materials['InteriorDoorFrench002_Handle_Mat_LOD0_8K_VAR1_8K.001']} />
        <mesh geometry={nodes.InteriorDoorFrench002_HandleR_Geo_LOD0002.geometry} material={materials['InteriorDoorFrench002_Handle_Mat_LOD0_8K_VAR1_8K.001']} />
      </group>
      <group position={[-1.892, -0.465, 1.015]} scale={[0.293, 0.41, 0.238]}>
        <mesh geometry={nodes.WindowSlidingPaintedMetal002_Frame_Geo_LOD0002.geometry} material={materials.WindowSlidingPaintedMetal002_Window_Mat_LOD0_8K_VAR1_8K} position={[0, -0.014, 0]} scale={[1, 1.03, 1]} />
        <mesh geometry={nodes.WindowSlidingPaintedMetal002_LeftSash_Geo_LOD0002.geometry} material={materials.WindowSlidingPaintedMetal002_Window_Mat_LOD0_8K_VAR1_8K} position={[0, -0.014, 0]} scale={[1, 1.03, 1]} />
        <mesh geometry={nodes.WindowSlidingPaintedMetal002_RightSash_Geo_LOD0002.geometry} material={materials.WindowSlidingPaintedMetal002_Window_Mat_LOD0_8K_VAR1_8K} position={[0, -0.014, 0]} scale={[1, 1.03, 1]} />
      </group>
      <group position={[-2.503, -0.47, 0.6]} rotation={[0, 1.553, 0]} scale={[0.293, 0.416, 0.238]}>
        <mesh geometry={nodes.WindowSlidingPaintedMetal002_Frame_Geo_LOD0003.geometry} material={materials.WindowSlidingPaintedMetal002_Window_Mat_LOD0_8K_VAR1_8K} />
        <mesh geometry={nodes.WindowSlidingPaintedMetal002_LeftSash_Geo_LOD0003.geometry} material={materials.WindowSlidingPaintedMetal002_Window_Mat_LOD0_8K_VAR1_8K} position={[-0.511, 0, 0.011]} rotation={[-Math.PI, 0.021, -Math.PI]} />
        <mesh geometry={nodes.WindowSlidingPaintedMetal002_RightSash_Geo_LOD0003.geometry} material={materials.WindowSlidingPaintedMetal002_Window_Mat_LOD0_8K_VAR1_8K} position={[0.549, 0, -0.012]} rotation={[Math.PI, 0, Math.PI]} />
      </group>
      <group position={[-2.503, -0.47, 0.254]} rotation={[0, 1.553, 0]} scale={[0.293, 0.416, 0.238]}>
        <mesh geometry={nodes.WindowSlidingPaintedMetal002_Frame_Geo_LOD0004.geometry} material={materials.WindowSlidingPaintedMetal002_Window_Mat_LOD0_8K_VAR1_8K} />
        <mesh geometry={nodes.WindowSlidingPaintedMetal002_LeftSash_Geo_LOD0004.geometry} material={materials.WindowSlidingPaintedMetal002_Window_Mat_LOD0_8K_VAR1_8K} position={[-0.515, 0, 0.011]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh geometry={nodes.WindowSlidingPaintedMetal002_RightSash_Geo_LOD0004.geometry} material={materials.WindowSlidingPaintedMetal002_Window_Mat_LOD0_8K_VAR1_8K} />
      </group>
      <group position={[-2.503, -0.47, -0.063]} rotation={[0, 1.553, 0]} scale={[0.293, 0.416, 0.238]}>
        <mesh geometry={nodes.WindowSlidingPaintedMetal002_Frame_Geo_LOD0005.geometry} material={materials.WindowSlidingPaintedMetal002_Window_Mat_LOD0_8K_VAR1_8K} />
        <mesh geometry={nodes.WindowSlidingPaintedMetal002_LeftSash_Geo_LOD0005.geometry} material={materials.WindowSlidingPaintedMetal002_Window_Mat_LOD0_8K_VAR1_8K} position={[-0.031, 0, 0.001]} scale={[0.922, 1, 1]} />
        <mesh geometry={nodes.WindowSlidingPaintedMetal002_RightSash_Geo_LOD0005.geometry} material={materials.WindowSlidingPaintedMetal002_Window_Mat_LOD0_8K_VAR1_8K} position={[-0.031, 0, 0.001]} scale={[0.922, 1, 1]} />
      </group>
      <group position={[-2.472, -0.464, 0.46]} scale={0.522}>
        <mesh geometry={nodes['bq_Vine_Vitis-vinifera_A_spring-summer_2'].geometry} material={materials.bq_Stem_Ivy} />
        <mesh geometry={nodes['bq_Vine_Vitis-vinifera_A_spring-summer_3'].geometry} material={materials.bq_Leaf_Ivy} />
      </group>
      <group position={[-0.002, -0.005, -0.001]} scale={[2.472, 0.464, 1]}>
        <mesh geometry={nodes.Cube001_1.geometry} material={materials.floor} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials.Poliigon_StoneMarbleTile_8627_2K} />
        <mesh geometry={nodes.Cube001_3.geometry} material={materials.Poliigon_StoneWallDecorative_9400_2K} />
      </group>
      <mesh geometry={nodes.Plane.geometry} material={materials.glass_material_frosted} position={[0.032, 0.542, 0.083]} scale={[1.066, 0.65, 0.389]} />
      <mesh geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} scale={[2.472, 0.464, 1]} />
      <mesh geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} scale={[2.472, 0.464, 1]} />
      <mesh geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} scale={[2.472, 0.464, 1]} />
      <mesh geometry={nodes.Cube004.geometry} material={nodes.Cube004.material} scale={[2.472, 0.464, 1]} />
      <mesh geometry={nodes.Plane002.geometry} material={materials.glass_material_frosted} position={[-2.511, 0.059, 0.31]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[-0.452, -3.337, -0.489]} />
      <mesh geometry={nodes.Plane003.geometry} material={materials.glass_material_frosted} position={[-1.741, 0.038, 1.037]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[-0.642, -3.337, -0.489]} />
      <mesh geometry={nodes.Sphere.geometry} material={materials.Material} position={[-0.084, 0.207, 0.028]} scale={-0.002} />
      <mesh geometry={nodes.IVY_Curve.geometry} material={materials['Bark.001']} position={[0.011, -0.067, 0]}>
        <mesh geometry={nodes.IvyLeaf.geometry} material={materials['leaf.002']} />
      </mesh>
      <mesh geometry={nodes.IVY_Curve001.geometry} material={nodes.IVY_Curve001.material}>
        <mesh geometry={nodes.IvyLeaf001.geometry} material={materials['leaf.001']} position={[0.031, 0.04, 0]} />
      </mesh>
      <mesh geometry={nodes.IVY_Curve002.geometry} material={nodes.IVY_Curve002.material}>
        <mesh geometry={nodes.IvyLeaf002.geometry} material={materials['leaf.002']} />
      </mesh>
      <mesh geometry={nodes.IVY_Curve003.geometry} material={materials['Bark.001']} position={[0, -0.084, 0]}>
        <mesh geometry={nodes.IvyLeaf003.geometry} material={materials['leaf.001']} position={[0, -0.1, 0]} />
        <mesh geometry={nodes.IvyLeaf010.geometry} material={materials['leaf.001']} position={[-1.41, -0.151, -0.55]} rotation={[0, Math.PI / 2, 0]} />
      </mesh>
      <mesh geometry={nodes.IVY_Curve004.geometry} material={nodes.IVY_Curve004.material}>
        <mesh geometry={nodes.IvyLeaf004.geometry} material={materials['leaf.002']} />
      </mesh>
      <mesh geometry={nodes.IVY_Curve005.geometry} material={nodes.IVY_Curve005.material}>
        <mesh geometry={nodes.IvyLeaf005.geometry} material={materials['leaf.001']} />
      </mesh>
      <mesh geometry={nodes.IVY_Curve006.geometry} material={materials['Bark.001']} position={[0, -0.126, 0]}>
        <mesh geometry={nodes.IvyLeaf006.geometry} material={materials['leaf.002']} position={[0.118, -0.115, 0]} />
      </mesh>
      <mesh geometry={nodes.IVY_Curve007.geometry} material={nodes.IVY_Curve007.material} position={[0, -0.087, 0.065]}>
        <mesh geometry={nodes.IvyLeaf007.geometry} material={materials['leaf.001']} />
      </mesh>
      <mesh geometry={nodes.IVY_Curve008.geometry} material={materials['Bark.001']}>
        <mesh geometry={nodes.IvyLeaf008.geometry} material={materials['leaf.001']} position={[0, 0, -0.064]} />
      </mesh>
      <mesh geometry={nodes.IVY_Curve009.geometry} material={materials['Bark.001']}>
        <mesh geometry={nodes.IvyLeaf009.geometry} material={materials['leaf.001']} />
      </mesh>
      <mesh geometry={nodes.Sphere001.geometry} material={materials.Material} position={[-0.085, 0.37, 0.32]} scale={-0.002} />
      <mesh geometry={nodes.Sphere002.geometry} material={materials.Material} position={[-0.131, 0.409, -0.1]} scale={-0.002} />
      <mesh geometry={nodes.Sphere003.geometry} material={materials.Material} position={[-0.109, 0.217, -0.215]} scale={-0.002} />
      <mesh geometry={nodes.Sphere004.geometry} material={materials.Material} position={[0.026, -0.15, 0.561]} scale={-0.002} />
      <mesh geometry={nodes.Sphere005.geometry} material={materials.Material} position={[-0.053, -0.246, -0.455]} scale={-0.002} />
      <mesh geometry={nodes.Sphere006.geometry} material={materials.Material} position={[-0.391, 0.132, 0.52]} scale={-0.002} />
      <mesh geometry={nodes.Sphere007.geometry} material={materials.Material} position={[-0.082, 0.04, -0.245]} scale={-0.002} />
      <mesh geometry={nodes.Sphere008.geometry} material={materials.Material} position={[-0.583, 0.04, -0.024]} scale={-0.002} />
      <mesh geometry={nodes.Sphere009.geometry} material={materials.Material} position={[-1.127, 0.04, -0.373]} scale={-0.002} />
      <mesh geometry={nodes.IVY_Curve010.geometry} material={materials['Bark.001']} position={[0, 0.017, 0.057]}>
        <mesh geometry={nodes.IvyLeaf011.geometry} material={materials['leaf.001']} position={[1.347, 0, 0.077]} />
      </mesh>
      <mesh geometry={nodes.IVY_Curve011.geometry} material={materials['Bark.001']} position={[0, -0.077, 0]}>
        <mesh geometry={nodes.IvyLeaf012.geometry} material={materials['leaf.001']} position={[0, 0.005, 0]} rotation={[0.08, 0.007, -0.039]} />
      </mesh>
      <mesh geometry={nodes.Sphere010.geometry} material={materials.Material} position={[-0.001, 0.272, 0.54]} scale={-0.002} />
      <mesh geometry={nodes.Sphere011.geometry} material={materials.Material} position={[-0.419, -0.028, -0.541]} scale={-0.002} />
      <mesh geometry={nodes.concrete_cat_statue001.geometry} material={materials.concrete_cat_statue} position={[-1.543, -0.486, -0.906]} />
      <mesh geometry={nodes['bq_Rock_Basalt-Photoscan_A_spring-summer-autumn'].geometry} material={materials['bq_Rock_Basalt-Photoscan_A']} />
      <mesh geometry={nodes['bq_Rock_Pebble_A_spring-summer-autumn'].geometry} material={materials.bq_Rock_Pebble} />
      <mesh geometry={nodes['bq_Grass_Lolium-perenne_A_spring-summer'].geometry} material={materials.bq_Grass} />
      <mesh geometry={nodes['bq_Grass_Lolium-perenne_D_spring-summer'].geometry} material={materials.bq_Grass} />
      <mesh geometry={nodes['bq_Grass-Dry_Lolium-perenne_A_spring-summer'].geometry} material={materials.bq_Grass} />
      <mesh geometry={nodes['bq_Grass-Dry_Lolium-perenne_D_spring-summer'].geometry} material={materials.bq_Grass} />
      <mesh geometry={nodes['bq_Weed_Taraxacum-officinale_A_spring-summer_1'].geometry} material={materials.bq_Weed} />
      <mesh geometry={nodes['bq_Weed_Taraxacum-officinale_A_spring-summer_2'].geometry} material={materials.bq_Flower_Atlas} />
      <mesh geometry={nodes['bq_Vine_Vitis-vinifera_A_spring-summer_2'].geometry} material={materials.bq_Stem_Ivy} />
      <mesh geometry={nodes['bq_Vine_Vitis-vinifera_A_spring-summer_3'].geometry} material={materials.bq_Leaf_Ivy} />
      <mesh geometry={nodes['bq_Vine_Vitis-vinifera_D_spring-summer_1'].geometry} material={materials.bq_Stem_Ivy} />
      <mesh geometry={nodes['bq_Vine_Vitis-vinifera_D_spring-summer_2'].geometry} material={materials.bq_Leaf_Ivy} />
    </group>
  )
}

useGLTF.preload('/valentines_day_scene.glb')
