/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\ValentinesDayv2-v1.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Scene(props) {
  const { nodes, materials } = useGLTF('/models/ValentinesDayv2-v1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.fireplace_fireplace_0.geometry} material={materials.fireplace} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.brick} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.PlasticMoldWood006_2K} />
      <mesh geometry={nodes.book_shelf_0.geometry} material={materials.PlasticMoldWood006_2K} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.Leather} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.blanket} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.metal} />
      <mesh geometry={nodes.Object_33.geometry} material={materials.Fabric_pilows} />
      <mesh geometry={nodes.Cube007.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.WineBottles001_01001.geometry} material={materials.WineBottles001_4K} />
      <mesh geometry={nodes.BottleSodaEmpty001_Bottle001.geometry} material={materials.BottleSodaEmpty001_1K} />
      <mesh geometry={nodes.IvyLeaf.geometry} material={materials.PaletteMaterial003} />
      <mesh geometry={nodes.IVY_Curve.geometry} material={nodes.IVY_Curve.material} />
      <mesh geometry={nodes.Sphere.geometry} material={materials.PaletteMaterial004} position={[-0.854, 6.772, 7.481]} scale={0.282} />
      <mesh geometry={nodes.Text.geometry} material={materials.PaletteMaterial005} position={[-0.508, 3.857, 7.677]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.619} />
      <mesh geometry={nodes.Cube013.geometry} material={materials.PaletteMaterial006} />
      <mesh geometry={nodes.Empty001.geometry} material={materials.Empty} />
      <mesh geometry={nodes.Empty003.geometry} material={materials['Empty.002']} />
      <mesh geometry={nodes.RugDesignerAlbatrossGrey001001.geometry} material={materials.RugDesignerAlbatrossGrey001_4K} position={[-0.693, -0.377, 3.035]} scale={1.136} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.PaletteMaterial007} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.glep} />
    </group>
  )
}

useGLTF.preload('/models/ValentinesDayv2-v1.glb')
